### ISSUE TITLE
Failed to enable plugin: GCAuth_OAuth java.lang.NullPointerException: Cannot read field "rateLimit" because the return value of "me.exzork.gcauth.GCAuth.getConfig()" is null

### ISSUE THREAD

**Issue by ghost** [Xtao-Team/GCAuth-OAuth#7]
+ StackTrace:
```
<ERROR:PluginManager> Failed to enable plugin: GCAuth_OAuth
java.lang.NullPointerException: Cannot read field "rateLimit" because the return value of "me.exzork.gcauth.GCAuth.getConfig()" is null
        at me.exzork.gcauth.handler.GCAuthExternalAuthenticator.<init>(GCAuthExternalAuthenticator.java:24)
        at com.xtaolabs.gcauth_oauth.handler.GCAuthAuthenticationHandler.<init>(GCAuthAuthenticationHandler.java:16)
        at com.xtaolabs.gcauth_oauth.GCAuth_OAuth.loadTwitterLogin(GCAuth_OAuth.java:41)
        at com.xtaolabs.gcauth_oauth.GCAuth_OAuth.onEnable(GCAuth_OAuth.java:28)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:200)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:197)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:164)
```

+ My Files in plugin folder:

```
root@instance-3q7c18wo:~/Server/27/plugins# tree
.
├── GCAuth
│   ├── config.json
│   └── OAuth
│       ├── css
│       │   ├── app.11404339.css
│       │   └── regeister.css
│       ├── imgs
│       │   ├── close.svg
│       │   └── logo.png
│       ├── js
│       │   ├── about.6b74533b.js
│       │   ├── ...
│       │   └── chunk-vendors-legacy.dccdb30c.js.map
│       ├── login.html
│       └── Twitter_Authorize_Res
│           ├── js_inst
│           ├── tfw-base.3baf723b92aa68729f921c77ca3e3c1315116392.css
│           └── yXprk4Zb
├── gcauth-2.4.0.jar
├── GCAuth_OAuth
├── gcauth_oauth-1.2.0.jar
├── mojoconfig.json
├── mojoconsole
├── mojoconsole.jar
└── mojoconsole-plus

9 directories, 25 files
```

+ Plugin infos:
```
root@instance-3q7c18wo:~/Server/27# ./gpm list
[Info] Found config.json
┌──────────────────┬───────────────────┬─────────────────────────────────────────────────────────────────────────────────┐
│       name       │      version      │                                   description                                   │
├──────────────────┼───────────────────┼─────────────────────────────────────────────────────────────────────────────────┤
│   GCAuth_OAuth   │       1.1.3       │     The in-game login system for Grasscutter is based on oauth and GCAuth.      │
│      GCAuth      │       2.2.0       │ GCAuth is a plugin that allows you to implement authentication for your server. │
│ mojoconsole-plus │ dev-1.2.0-f5dc9f3 │                      Grasscutter In Game Web Based Console                      │
└──────────────────┴───────────────────┴─────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by omg-xtao** [comment]
GCAuth OAuth is now at version 1.2.0, and gpm does not appear to have been upgraded.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/68674499/178248449-94823173-b33e-4aaa-9b83-338d337f843d.png)

![image](https://user-images.githubusercontent.com/68674499/178248813-c903ca52-ef54-40ba-a4aa-dbd15bdf1fe5.png)

确定是 1.2.0 版本的，但是问题仍然存在。
我不知道为什么
